# NOTE: update this with your service name
service: strengthify-api

custom:
  bundle:
    ignorePackages:
      - pg-native
    forceInclude:
      - pg

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-east-1
  environment:
    HEROKU_API_KEY: ${env:HEROKU_API_KEY}
    HEROKU_POSTGRES_ID: ${env:HEROKU_POSTGRES_ID}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
